apiVersion: v1
kind: Service
metadata:
  name: svc-kibana
  namespace: default
spec:
  selector:
    app: kibana-app
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
  type: LoadBalancer